from typing import List, Literal, NotRequired, Optional, TypeAlias, TypedDict, Union

from openai.types.chat import ChatCompletionChunk
from openai.types.chat.chat_completion import Choice
from openai.types.chat.chat_completion_chunk import ChoiceDelta


class ReasoningDetailBase(TypedDict):
    id: Optional[str]
    format: Literal["unknown", "openai-responses-v1", "anthropic-claude-v1"]
    index: Optional[int]


class ReasoningDetailSummaryType(ReasoningDetailBase):
    type: Literal["reasoning.summary"]
    summary: str


class ReasoningDetailEncryptedType(ReasoningDetailBase):
    type: Literal["reasoning.encrypted"]
    data: str


class ReasoningDetailTextType(ReasoningDetailBase):
    type: Literal["reasoning.text"]
    text: str
    signature: NotRequired[Optional[str]]


OpenRouterReasoningDetail: TypeAlias = Union[
    ReasoningDetailSummaryType,
    ReasoningDetailEncryptedType,
    ReasoningDetailTextType,
]


class OpenRouterDelta(ChoiceDelta):
    # ChoiceDelta(content='', function_call=None, refusal=None, role='assistant', tool_calls=None, reasoning='**Explain', reasoning_details=[{'type': 'reasoning.summary', 'summary': '**Explain', 'format': 'openai-responses-v1', 'index': 0}])
    reasoning_details: Optional[List[OpenRouterReasoningDetail]]


class OpenRouterChoice(Choice):
    delta: OpenRouterDelta


class OpenRouterChatCompletionChunk(ChatCompletionChunk):
    choices: List[OpenRouterChoice]


class OpenRouterCompletionTokensDetails(TypedDict, total=False):
    accepted_prediction_tokens: Optional[int]
    """
    When using Predicted Outputs, the number of tokens in the prediction that
    appeared in the completion.
    """

    audio_tokens: Optional[int]
    """Audio input tokens generated by the model."""

    reasoning_tokens: Optional[int]
    """Tokens generated by the model for reasoning."""

    rejected_prediction_tokens: Optional[int]
    """
    When using Predicted Outputs, the number of tokens in the prediction that did
    not appear in the completion. However, like reasoning tokens, these tokens are
    still counted in the total completion tokens for purposes of billing, output,
    and context window limits.
    """


class OpenRouterPromptTokensDetails(TypedDict, total=False):
    audio_tokens: Optional[int]
    """Audio input tokens present in the prompt."""

    cached_tokens: Optional[int]
    """Cached tokens present in the prompt."""


class OpenRouterCompletionUsage(TypedDict):
    completion_tokens: int
    """Number of tokens in the generated completion."""

    prompt_tokens: int
    """Number of tokens in the prompt."""

    total_tokens: int
    """Total number of tokens used in the request (prompt + completion)."""

    completion_tokens_details: NotRequired[Optional[OpenRouterCompletionTokensDetails]]
    """Breakdown of tokens used in a completion."""

    prompt_tokens_details: NotRequired[Optional[OpenRouterPromptTokensDetails]]
    """Breakdown of tokens used in the prompt."""
